micronaut:
  application:
    name: mn2StockBroker

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretToSomethingSecret
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:'jdbc:postgresql://127.0.0.1:5432/mn2-stock-broker'}
      username: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD} #secret
      driver-class-name: org.postgresql.Driver
      schemas: mn2
      default-schema: mn2
      schema-generate: NONE
      dialect: POSTGRES
datasources:
  default:
    url: ${PG_JDBC_URL:'jdbc:postgresql://127.0.0.1:5432/mn2-stock-broker'}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD} #secret
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
#micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "com.example.broker.persistence"
    properties:
      hibernate:
        show_sql: false
