micronaut:
  application:
    name: mn2StockBroker

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretToSomethingSecret



